version: 2.1
jobs:
  create_and_deploy_front_end:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: |
          aws cloudformation deploy --template-file bucket.yml --stack-name bucket-${CIRCLE_WORKFLOW_ID:0:5} --parameter-overrides NAME="bucket-${CIRCLE_WORKFLOW_ID:0:5}"
      - run: aws s3 sync . s3://"bucket-${CIRCLE_WORKFLOW_ID:0:5}" --delete

  promote_to_production:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run: |
          aws cloudformation deploy \
            --template-file cloudfront.yml \
            --stack-name cloudfront \
            --parameter-overrides PipelineID="bucket-${CIRCLE_WORKFLOW_ID:0:5}"

workflows:
  default:
    jobs:
      - create_and_deploy_front_end
      - promote_to_production:
          requires: [create_and_deploy_front_end]
