version: 2.1

jobs:
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - checkout
      - run:
          name: Ensure backend infrastructure exist
          command: |
            if curl -s --head "https://google.com"
            then
              echo "It worked!"
            else
              echo "It failed"
            fi
            
workflows:
  my_workflow:
    jobs:
      - smoke_test
